runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: app.app

# env_variables:
#   GAE_ENGINE_CHECK: caltrack_gae
#   CLOUDSQL_CONNECTION_NAME: caltrackernf:europe-west1:caltracknf
#   CLOUDSQL_USER: cator
#   CLOUDSQL_PASSWORD: caltrackhackzurich2017

# libraries:
# - name: numpy
#   version: "1.6.1"  
# - name: MySQLdb
#   version: "latest"


# runtime: python
# env: flex
# entrypoint: gunicorn -b :$PORT main:app

# runtime_config:
#   python_version: 2

# env_variables:
#   GAE_ENGINE_CHECK: caltrack_gae
#   CLOUDSQL_CONNECTION_NAME: inlaid-reactor-180108:caltrack1
#   CLOUDSQL_USER: cator
#   CLOUDSQL_PASSWORD: caltrackhackzurich2017
